#!/usr/bin/env python3
"""Build index.html (Japanese) and index.en.html (English) from the Markdown guides.

Plain white page for GitHub Pages. Usage (from the repository root):
    python docs/build_html.py
"""
import os
import re
import markdown

HERE = os.path.dirname(os.path.abspath(__file__))

LANGS = {
    "ja": dict(src="pipeline_guide.md", out="index.html", title="metacellcnv 実行ガイド",
               other=("English", "index.en.html"),
               footer='metacellcnv 実行ガイド。Markdown 版: <a href="pipeline_guide.md">pipeline_guide.md</a>(同じ内容)。'
                      '<code>docs/build_html.py</code> で生成。'),
    "en": dict(src="pipeline_guide.en.md", out="index.en.html", title="metacellcnv User Guide",
               other=("日本語", "index.html"),
               footer='metacellcnv User Guide. Markdown version: <a href="pipeline_guide.en.md">pipeline_guide.en.md</a> '
                      '(same content). Generated by <code>docs/build_html.py</code>.'),
}

CSS = """
:root { color-scheme: light; }
html { background: #ffffff; }
body { margin: 0; background: #ffffff; color: #222222;
  font-family: -apple-system, BlinkMacSystemFont, "Hiragino Sans", "Yu Gothic", "Noto Sans CJK JP", "Segoe UI", Helvetica, Arial, sans-serif;
  line-height: 1.75; font-size: 16px; }
.page { max-width: 900px; margin: 0 auto; padding: 24px 16px 64px; }
h1 { font-size: 1.7rem; margin: 0.4em 0 0.6em; }
h2 { font-size: 1.3rem; margin: 2.2em 0 0.6em; padding-bottom: 0.25em; border-bottom: 1px solid #cccccc; }
h3 { font-size: 1.1rem; margin: 1.6em 0 0.4em; }
a { color: #0b5cad; }
nav.toc { border: 1px solid #dddddd; padding: 8px 16px; margin: 16px 0 28px; background: #fafafa; font-size: 0.92rem; }
nav.toc ul { list-style: none; margin: 0; padding: 0; columns: 2; }
nav.toc li { margin: 2px 0; break-inside: avoid; }
nav.toc li.l3 { padding-left: 1.2em; font-size: 0.9em; }
.tablewrap { overflow-x: auto; margin: 12px 0 20px; }
table { border-collapse: collapse; font-size: 0.9rem; min-width: 100%; }
th, td { border: 1px solid #cccccc; padding: 6px 10px; vertical-align: top; text-align: left; }
th { background: #f3f3f3; }
code { background: #f4f4f4; padding: 1px 4px; border-radius: 3px; font-size: 0.88em; }
pre { background: #f4f4f4; padding: 10px 12px; overflow-x: auto; border-radius: 4px; }
pre code { background: none; padding: 0; }
figure { margin: 20px 0 28px; padding: 0; }
figure img { max-width: 100%; height: auto; display: block; margin: 0 auto; border: 1px solid #eeeeee; background: #ffffff; }
figcaption { font-size: 0.86rem; color: #444444; margin-top: 8px; line-height: 1.6; }
blockquote { border-left: 3px solid #cccccc; margin: 12px 0; padding: 2px 14px; color: #444444; }
.langswitch { text-align: right; font-size: 0.9rem; margin: 0; }
footer { margin-top: 48px; padding-top: 12px; border-top: 1px solid #dddddd; font-size: 0.82rem; color: #666666; }
@media (max-width: 640px) { nav.toc ul { columns: 1; } body { font-size: 15px; } }
"""


def flatten(tokens, out):
    for t in tokens:
        out.append(t)
        flatten(t.get("children", []), out)
    return out


def build(lang, cfg):
    src = open(os.path.join(HERE, cfg["src"]), encoding="utf-8").read()
    md = markdown.Markdown(extensions=["tables", "fenced_code", "toc", "sane_lists"],
                           extension_configs={"toc": {"toc_depth": "2-3", "permalink": False}})
    body = md.convert(src)

    # Figures link to the full-size image; tables scroll sideways on narrow screens
    body = re.sub(r'(<img src="([^"]+)"[^>]*>)', r'<a href="\2">\1</a>', body)
    body = re.sub(r"(<table>.*?</table>)", r'<div class="tablewrap">\1</div>', body, flags=re.S)

    items = [t for t in flatten(md.toc_tokens, []) if t["level"] != 1]
    toc = "<ul>\n" + "\n".join(
        f'<li class="l{t["level"]}"><a href="#{t["id"]}">{t["name"]}</a></li>' for t in items) + "\n</ul>"
    nav = '</h1>\n<nav class="toc">\n' + toc + '\n</nav>'
    body = body.replace("</h1>", nav, 1)

    label, href = cfg["other"]
    switch = f'<p class="langswitch"><a href="{href}">{label}</a></p>'
    html = f"""<!doctype html>
<html lang="{lang}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{cfg["title"]}</title>
<style>{CSS}</style>
</head>
<body>
<div class="page">
{switch}
{body}
<footer>{cfg["footer"]}</footer>
</div>
</body>
</html>
"""
    open(os.path.join(HERE, cfg["out"]), "w", encoding="utf-8").write(html)
    print("wrote", cfg["out"], len(html))


if __name__ == "__main__":
    for lang, cfg in LANGS.items():
        build(lang, cfg)
